### PR TITLE
add build_tests option

### PR DESCRIPTION
**Pull request by ffontaine**
Allow the user to disable build of test programs

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by kjellahl** [comment]
I've merged this PR and added a commit that makes the build_tests check more like the
check in cairomm and libxml++. I've copied the two commits to the libsigc++-2-12 branch.

**Comment by ffontaine** [comment]
In my first iteration, I tried to set `build_by_default` as done by commit 5711e2bc736d9a06fd19b838732568911baab6f1 but for an unknown reason, it wasn't working (the tests were always built). I'll double check on master.

**Comment by kjellahl** [comment]
Did you put `if build_tests` around `test(ex_name, exe_file)`?
```
  # If exe_file is a test program, it is built by default unconditionally.
  if build_tests
    test(ex_name, exe_file)
  endif
```

**Comment by ffontaine** [comment]
Nope, I only updated `build_by_default`, thanks for your answer.

**Pull request merged**
