### PR TITLE
Zig build + CI test

### PR DESCRIPTION
**Pull request by kassane**
Need zig [v0.11 or higher](https://ziglang.org/download) with pkg manager (for C++ [`zig c++`], uses `libcxx + libcxxabi + libunwind` only).

Release date?
See: https://github.com/ziglang/zig/milestone/17

### More info about `zig-pkg`

- https://github.com/ziglang/zig/pull/14265
- https://devlog.hexops.com/2023/mach-ecosystem-c-libraries/
- https://kassane.github.io/2023/05/03/zig-pkg/
- https://github.com/catdevnull/awesome-zig#cc-libraries-packaged-for-zig (also boost-lib is in progress of being ported)

### CODE REVIEW

**Comment by kjellahl** [comment]
So Zig is a build system (and a programming language, and a C/C++ compiler)?
I had not heard of it before I saw this PR.

I'm not very fond of the thought of making libsigc++ support yet another build system,
in addition to Autotools (which might be dropped some time), Meson, CMake and
Microsoft Visual C++. Someone must be able to make changes in the new files when
necessary. Do you plan to keep the zig files updated for the years to come?

I might change my mind if Zig becomes a widespread build system in Gnome.
What has Gnome to do with libsigc++? A lot. Most of the software that I maintain
is stored at https://gitlab.gnome.org/GNOME. Several C++ packages there depend on libsigc++.

**Comment by kassane** [comment]
Hi @kjellahl ,

Thanks for the clarification on the relationship with Gnome. In addition to the sincerity about zig.

#### Replying your initial question:

Yes, Ziglang is a new language having the purpose to be an alternative to C, not as replacement only, also as complement (easy ffi - better than using C code in C++). Zig can guarantee that C code runs with clang rules and not clang++.

```bash
$> zig version
0.11.0-dev.4003+c6aa29b6f
$> zig cc --version
clang version 16.0.1 (https://github.com/ziglang/zig-bootstrap bf1b2cdb83141ad9336eec42160c9fe87f90198d)
Target: x86_64-unknown-linux-musl
Thread model: posix
InstalledDir: /usr/bin
```

#### What is the purpose of zig about `libsigc++`?

Today, zig has llvm-backend to build C and C++ projects (clang/clang++) in which it manages porting some libC for easy cross-compilation ( CI added by me is proof of that), so it is first class support. Except for BSDs with incomplete support and MSVC because of MS license.

Zig libc: https://github.com/ziglang/zig/tree/master/lib/libc **(first class support = portability)**

Zig can also move between glibc versions. It makes it possible to choose the version of glibc in the target build.
https://github.com/ziglang/glibc-abi-tool

For C++ exclusively, zig has support `llvm-libcxx` + `llvm-libcxxabi` + `llvm-unwind` + custom `libcompiler-rt` (rewritten on zig) that are statically linked in the binaries.

https://github.com/ziglang/zig/tree/master/lib/libcxx
https://github.com/ziglang/zig/tree/master/lib/libcxxabi
https://github.com/ziglang/zig/tree/master/lib/libunwind
https://github.com/ziglang/zig/tree/master/lib/compiler_rt

I'm a C++ developer currently porting some libraries which will allow me to use `zig-pkg` (package manager) which will be released in the new version of this tool. Something equivalent to `fetchContent`(`cmake`), that is, for non-header-only libraries would need that dependencies have `cmake` to be built and linked to the main project. The same applies to `zig-pkg` which needs to push includes and libs built before linking to the main project.

Summarizing, `libsigc++` is statically running `libcxx`+`libunwind` on almost all platforms under the same condition (C++ABI unified).

#### Zig is planning to not depend from LLVM. How will C++ support work?

Yes, however only version 1.0 that maybe will be released in mid 2025!
Explained here: https://youtu.be/AqDdWEiSwMM?t=2435

The zig project has always wanted to become a self-hosted toolchain making LLVM support optional, while benefiting from all the targets of this tool. However, many bugs inhibit further development of the main project (zig), which has fewer compiler developers.

- https://github.com/ziglang/zig/issues/16270#issuecomment-1616115039 (**rationale about c++ and obj-c++ support**)

[Andrew Kelley](https://github.com/andrewrk) has plans for zig to become not only a language and toolchain focused on the language itself, but also a new backend compiler that competes with LLVM and GCC keeping compatibility.

**Roadmap:** old diagram (v0.9.0)

**Comment by kassane** [comment]
If you cannot merge I'll understand. However, fork is maintained with `zig-pkg` support.

**Comment by kjellahl** [comment]
I prefer not to merge this PR.

As I said, supporting Zig build might be considered in the future if Zig is
supported by Gnome modules, especially GLib and GTK.

**Pull request closed without merging**
