### PR TITLE
meson: simplify lookup of python command

### PR DESCRIPTION
**Pull request by wael444**

### CODE REVIEW

**Comment by kjellahl** [comment]
According to the commit message of https://github.com/libsigcplusplus/libsigcplusplus/commit/82005b8f65e65d8ea9544cb26a007f8c1c6ca27d
 it's wise to get the python installation with `import('python').find_installation()`,
 to be sure to use the python version that Meson uses.
 I don't use Visual Studio myself. I'm not sure what problems may occur with
 `find_program('python3', version: '>=3.5')`. I'd prefer to stick to
 `import('python').find_installation()`. But the version test is unnecessary.
 It can be removed. Meson itself requires python3 >= 3.7.
 See https://mesonbuild.com/Getting-meson.html.

**Comment by wael444** [comment]
> I'm not sure what problems may occur with

They solve problems with other meson specification implementations.

> But the version test is unnecessary.

https://github.com/libsigcplusplus/libsigcplusplus/blob/b8260dd2a97a1775d5b7c23e080d2f0f32ed5fa4/meson.build#L44-L50

So is this complex lookup of the version - which looks for '3.5', hence why its added.

**Comment by kjellahl** [comment]
@fanc999 Do you think it's safe to change
```
python3 = import('python').find_installation()
```
to
```
python3 = find_program('python3', version: '>=3.5')
```
wael thinks `import('python').find_installation()` is unnecessarily complex.

@wael444 I wonder if you misunderstood my *But the version test is unnecessary.*
I meant the 5-line test in meson.build just now.

**Comment by eli-schwartz** [comment]
The purpose of the python module's find_installation method is to provide a rich object with methods for building python extensions.

If you just need a script interpreter, and stick to the stdlib so you don't need to use the `modules:` kwarg, then `find_program()` is indeed simpler -- and will fall back to using the python that Meson itself uses.

**Comment by fanc999** [comment]
Hi @kjellahl ,

I think it might be ok, but I don't think it's really necessary.  We could just take out the version check below, since Meson 0.55.x+ already requires Python 3.5.x or later.

With blessings, and cheers!

**Comment by kjellahl** [comment]
I've merged this PR and copied the commit to the libsigc++-2-12 branch.

**Pull request merged**
